spring:
  jpa:
    show-sql: false
  flyway:
    clean-disabled: true  # NEVER clean in prod

server:
  ssl:
    enabled: false
  forward-headers-strategy: framework

logging:
  level:
    kz.aitu.hrms: INFO
    org.springframework.security: WARN
  file:
    name: /var/log/hrms/app.log
  logback:
    rollingpolicy:
      max-file-size: 100MB
      max-history: 30

springdoc:
  swagger-ui:
    server-url: https://hrms.nursnerv.uk/api
  servers:
    - url: https://hrms.nursnerv.uk/api
      description: Production server