package kz.aitu.hrms.notification.domain;

public enum NotificationType {
    LEAVE_REQUEST, LEAVE_APPROVED, LEAVE_REJECTED,
    PAYROLL_READY, PAYSLIP_GENERATED, PAYROLL_ANOMALY,
    ATTENDANCE_ALERT, FRAUD_ALERT,
    EMPLOYEE_ONBOARDED, EMPLOYEE_TERMINATED,
    PASSWORD_RESET, SYSTEM, INFO
}
